### ISSUE TITLE
a question for help

### ISSUE THREAD

**Issue by j123kaishichufa** [lpabon/cmockery2#16]
hi,
i do not know how to raise a question for help using cmockery2 in github, so i raise the question here. if it is not proper, please forgive me.

in my test, i wan to test that funa indeed called funcb successfully.  i meet a puzzle in my test , the souce code(func.c test.c) is as follow:

//func.c

#include
void funcb(int para)
{
para = para+10;
printf("real funcb\n");
}
void funca()
{
int msg = 10;
funcb(msg);
}

//test.c
#include
#include
#include
#include
#include
#include "cmockery.h"
//#include
//#define UNIT_TESTING 1

//#if UNIT_TESTING
//#include "cmockery_override.h"
//#endif
//#include

extern void funca();
//extern static void funcb(int para);
//mock funcb
static void funcb(int para)
{
printf("*************");
check_expected(para);
}

//test
void test_funca(void ** state)
{
expect_value(funcb, para, 10);
funca();
}

int main()
{
const UnitTest tests[]={unit_test(test_funca)};
return run_tests(tests,"report");
}

i want to test funca. when i run test, i found funca in test.c called the funcb in funcc.c, but not the mock funb. why?
 thank you very much.

**Comment by j123kaishichufa** [comment]
I have tried  this way as you said. It does  work well.  Thank you. 


I also sovle this  problem by adding macro to real funcb.  Let the complier does not compile the real funcb but the mocked funcb.

//func.c
# ifndef UNIT_TESTING 
void funcb(int para)
{
para = para+10;
printf("real funcb\n");
}
#endif

void funca() 
{
int msg = 10;
funcb(msg);
}

in test.c,   #define UNIT_TESTING 1


    But , from our users's view,  the method you said or my macro solution above, has slightly changged the structure of  the tested program files. 
    I think that whether cmockery can provide a internal mechanism to avoid modiying the structure of  the tested program files, neither needing splitting the function nor adding macro explicitly.
   I don't know wheter my thought is reasonable or not.  Just only express my  idea without other purpose.
   Thank you again for your reply.

**Comment by lpabon** [comment]
@j123kaishichufa No problem at all.  Your request is a good one, but C language make it really difficult to do this.  

Instead what I have done in my projects is only mock external libraries.  If I have a `func.c` and in that file I have `funca()` and `funcb()`, I would not mock them.  Instead, if `funca()` calls `funcx()` which is in another directory or library, then I would create a `mock_funcx()`. 

Again, the goal is to make it simple and able to be maintained by others.  Let me know if you need any other help.

**Comment by j123kaishichufa** [comment]
@lpabon    
     I think i have gotten your idea.  Cmockery2 is really an lightweight test framework for unit test. It easy to use. 
    Thank you.
